"use client";
import Link from "next/link";
import { ArrowRight, CalendarDays, Check, CloudSun, Layers3, ShoppingBag, Sparkles, Star, Shirt, ShieldCheck } from "lucide-react";
import { motion } from "framer-motion";

export default function LandingPage(){
  return <div className="min-h-screen bg-white text-slate-950">
    <header className="sticky top-0 z-30 border-b border-slate-100 bg-white/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 text-white"><Shirt size={18}/></span><span className="font-extrabold tracking-tight">ClosetSync</span></Link><div className="flex items-center gap-3"><Link href="/login" className="px-3 py-2 text-sm font-semibold text-slate-600">Sign in</Link><Link href="/signup" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Get started</Link></div></div></header>
    <main>
      <section className="bg-grid overflow-hidden"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-sky-100 bg-sky-50 px-3 py-1.5 text-xs font-bold text-sky-700"><Sparkles size={13}/>Smart wardrobe, built around you</div><h1 className="max-w-3xl text-5xl font-black tracking-[-0.04em] text-slate-950 sm:text-6xl">Stop saying <span className="text-sky-600">“I have nothing to wear.”</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-500">ClosetSync organises what you already own, builds practical outfits, plans future looks and helps you shop without the duplicates.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Build my wardrobe <ArrowRight size={16}/></Link><Link href="#how" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-slate-700">See how it works</Link></div><div className="mt-7 flex flex-wrap gap-5 text-sm text-slate-500"><span className="inline-flex items-center gap-2"><Check size={15} className="text-emerald-500"/>Free-first core</span><span className="inline-flex items-center gap-2"><Check size={15} className="text-emerald-500"/>Private wardrobe</span><span className="inline-flex items-center gap-2"><Check size={15} className="text-emerald-500"/>Responsive web app</span></div></div>
      <motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="relative"><div className="rounded-[28px] border border-slate-200 bg-white p-4 shadow-2xl shadow-slate-200/70"><div className="rounded-2xl bg-slate-950 p-5 text-white"><div className="flex items-start justify-between"><div><div className="text-xs text-slate-400">Good morning</div><div className="mt-1 text-xl font-bold">Your day, styled.</div></div><div className="rounded-xl bg-white/10 px-3 py-2 text-xs">24°C • Clear</div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white/10 p-4"><div className="flex items-center gap-2 text-slate-300"><Sparkles size={15}/>AI recommendation</div><div className="mt-3 grid grid-cols-3 gap-2">{["https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=400&q=80","https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=400&q=80","https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=400&q=80"].map(src=><img key={src} src={src} className="aspect-square rounded-xl object-cover" alt=""/>)}</div></div><div className="rounded-2xl bg-white/10 p-4"><div className="text-sm text-slate-300">Wardrobe pulse</div><div className="mt-4 text-4xl font-black">28</div><div className="mt-1 text-xs text-slate-400">items in your wardrobe</div><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-2 w-3/4 rounded-full bg-sky-400"/></div></div></div></div></div></motion.div></div></section>

      <section id="how" className="mx-auto max-w-7xl px-5 py-20"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-sky-600">How it works</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Your wardrobe becomes the source of truth.</h2><p className="mt-4 text-slate-500">The recommendation engine follows your preferences first, then occasion, what is actually available, weather and only then trends.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[[Layers3,"Add what you own","Upload wardrobe pieces, review the detected details and keep availability up to date."],[Sparkles,"Get practical outfits","Receive up to six outfit ideas using only items available in your wardrobe."],[CalendarDays,"Plan ahead","Save favourites, put looks on your calendar and reduce outfit repetition."]].map(([Icon,title,desc],i)=>{const I=Icon as typeof Sparkles; return <div key={String(title)} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid h-11 w-11 place-items-center rounded-xl bg-sky-50 text-sky-600"><I size={20}/></div><div className="mt-5 text-xs font-bold text-slate-400">0{i+1}</div><h3 className="mt-1 text-lg font-bold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{String(desc)}</p></div>})}</div></section>

      <section className="border-y border-slate-100 bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-20"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[ShoppingBag,"Smarter shopping"],[CloudSun,"Weather aware"],[Star,"Outfit history"],[ShieldCheck,"Private by design"]].map(([Icon,title])=>{const I=Icon as typeof Sparkles; return <div key={String(title)} className="rounded-2xl border border-slate-200 bg-white p-5"><I className="text-sky-600" size={20}/><div className="mt-4 font-bold">{String(title)}</div><p className="mt-1 text-sm text-slate-500">Built into the product flow, not bolted on later.</p></div>})}</div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20"><div className="rounded-[28px] bg-slate-950 p-8 text-white sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-semibold text-sky-300">Ready when you are</p><h2 className="mt-2 max-w-2xl text-3xl font-black tracking-tight sm:text-4xl">Make your wardrobe work harder before you buy more.</h2><p className="mt-4 max-w-xl text-slate-400">Start with the free-first core. Premium-only capabilities stay optional and modular.</p></div><Link href="/signup" className="inline-flex w-fit items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950">Create account <ArrowRight size={16}/></Link></div></div></section>
    </main><footer className="border-t border-slate-100 px-5 py-7 text-center text-xs text-slate-400">© 2026 ClosetSync · Your Smart AI Wardrobe Companion</footer>
  </div>
}
